trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'self-hosted-agent-pool'  # Replace with the name of your self-hosted agent pool

jobs:
- job: DeployToAKS
  displayName: 'Deploy to AKS'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.1.x'

  - script: |
      # Your build commands go here (if needed)
      dotnet build -c Release
    displayName: 'Build Application'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'YourAzureServiceConnection'  # Replace with your Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: 'deploy-to-aks.sh'  # Adjust based on your deployment script
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Deploy to AKS'
